name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '16.3.0'
      - name: compile frontend
        run: |
          cd frontend
          npm install
          cd ..
      - name: compile backend
        run: |
          cd backend 
          npm install
          npm run build

