name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '16.3.0'
      - name: compile frontend
        run: |
          cd frontend
          npm install
          cd ..
      - name: compile backend
        run: |
          cd backend 
          npm install
          npm run build
  deploy:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: |
          docker build --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} -t "registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web" .
      - name: push docker image to heroku
        run: |
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      - name: release 
        run: |
          heroku container:release web
      - name: health check
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s  